\contentsline {firstline}{\chapternumberline {1} Iminā puññakammena upajjhāyā guṇuttarā}{36}{chapter*.15}%
\contentsline {firstline}{\chapternumberline {1} A través del bien que resulta de mi práctica}{37}{chapter.17}%
\contentsline {firstline}{\chapternumberline {1} Puññass'idāni katassa yān'aññāni katāni me}{38}{chapter.18}%
\contentsline {firstline}{\chapternumberline {1} Karaṇīyam-attha-kusalena}{40}{chapter*.16}%
\contentsline {firstline}{\chapternumberline {1} Esto es lo que se debe hacer }{41}{chapter.19}%
\contentsline {firstline}{\chapternumberline {1} Mettā-sahagatena}{46}{chapter*.17}%
\contentsline {firstline}{\chapternumberline {1} Llenaré un cuarto}{47}{chapter.21}%
\contentsline {firstline}{\chapternumberline {1} Así he oído, que el Excelso}{48}{chapter.22}%
\contentsline {firstline}{\chapternumberline {1} Yathā vāri-vahā pūrā paripūrenti sāgaraṁ}{51}{chapter.23}%
\contentsline {firstline}{\chapternumberline {1} Ahaṁ sukhito homi}{54}{chapter*.18}%
\contentsline {firstline}{\chapternumberline {1} Que yo mantenga bienestar}{55}{chapter.24}%
\contentsline {firstline}{\chapternumberline {1} Paṭisaṅkhā yoniso}{56}{chapter.25}%
\contentsline {firstline}{\chapternumberline {1} Ayaṁ kho me kāyo}{58}{chapter.26}%
\contentsline {firstline}{\chapternumberline {1} Yathā paccayaṁ pavattamānaṁ}{60}{chapter.27}%
\contentsline {firstline}{\chapternumberline {1} Jarā-dhammomhi jaraṁ anatīto}{65}{chapter.28}%
\contentsline {firstline}{\chapternumberline {1} Dasa ime bhikkhave}{67}{chapter.29}%
\contentsline {firstline}{\chapternumberline {1} Bahuṁ ve saraṇaṁ yanti}{70}{chapter.30}%
\contentsline {firstline}{\chapternumberline {1} Yassa saddhā tathāgate}{72}{chapter.31}%
\contentsline {firstline}{\chapternumberline {1} Sabbe saṅkhārā aniccā'ti}{73}{chapter.32}%
\contentsline {firstline}{\chapternumberline {1} Bhārā have pañcakkhandhā}{75}{chapter.33}%
\contentsline {firstline}{\chapternumberline {1} Atītaṁ nānvāgameyya}{76}{chapter.34}%
\contentsline {firstline}{\chapternumberline {1} Ye ca atītā sambuddhā}{78}{chapter.35}%
\contentsline {firstline}{\chapternumberline {1} Khantī paramaṁ tapo tītikkhā}{80}{chapter.36}%
\contentsline {firstline}{\chapternumberline {1} Aneka-jāti-saṁsāraṁ}{82}{chapter.37}%
\contentsline {firstline}{\chapternumberline {1} Handa dāni bhikkhave āmantayāmi vo}{83}{chapter.38}%
\contentsline {firstline}{\chapternumberline {1} Ye dhammā hetuppabhavā}{84}{chapter.39}%
\contentsline {firstline}{\chapternumberline {1} Atthi bhikkhave ajātaṁ abhūtaṁ akataṁ}{85}{chapter.40}%
\contentsline {firstline}{\chapternumberline {1} Kiṁ-mūlakā āvuso sabbe dhammā}{88}{chapter.42}%
\contentsline {firstline}{\chapternumberline {1} Ānāpānassati bhikkhave bhāvitā bahulī-katā}{90}{chapter.43}%
\contentsline {firstline}{\chapternumberline {1} Ayam-eva ariyo aṭṭhaṅgiko maggo}{96}{chapter.44}%
\contentsline {firstline}{\chapternumberline {1} Evaṁ svākkhāto bhikkhave mayā dhammo}{106}{chapter.45}%
\contentsline {firstline}{\chapternumberline {1} Chinda sotaṁ parakkamma}{111}{chapter.46}%
\contentsfinish 
